name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: vertexcloud

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t vertexcloud .

      - name: Tag Image
        run: |
          docker tag vertexcloud:latest 387512138534.dkr.ecr.ap-south-1.amazonaws.com/vertexcloud:latest

      - name: Push Image
        run: |
          docker push 387512138534.dkr.ecr.ap-south-1.amazonaws.com/vertexcloud:latest
